const SECTIONS = [
  {
    id: "os",
    label: "Sistema Operacional & Linux",
    icon: "◈",
    color: "#00E5A0",
    items: [
      { t: "Linux: linha de comando e shell scripting", lv: "base" },
      { t: "Gerenciamento de processos, serviços e daemons", lv: "base" },
      { t: "Permissões, usuários e grupos", lv: "base" },
      { t: "Redes no Linux (ip, ss, netstat, tcpdump)", lv: "base" },
      { t: "Gerenciadores de pacotes (apt, yum, dnf)", lv: "base" },
      { t: "Systemd e init systems", lv: "mid" },
      { t: "Performance e monitoramento de sistema (top, htop, vmstat)", lv: "mid" },
    ],
  },
  {
    id: "net",
    label: "Redes & Segurança",
    icon: "◎",
    color: "#4A9EFF",
    items: [
      { t: "Modelo OSI e protocolos TCP/IP", lv: "base" },
      { t: "DNS, DHCP, HTTP/HTTPS, SSL/TLS", lv: "base" },
      { t: "Firewalls, iptables, nftables", lv: "mid" },
      { t: "VPN, proxies e balanceadores de carga", lv: "mid" },
      { t: "Zero Trust e segurança de rede", lv: "adv" },
      { t: "Service Mesh (Istio, Linkerd)", lv: "adv" },
    ],
  },
  {
    id: "vcs",
    label: "Controle de Versão",
    icon: "⌥",
    color: "#A78BFA",
    items: [
      { t: "Git: commits, branches, merge, rebase", lv: "base" },
      { t: "Fluxos de trabalho: GitFlow, trunk-based", lv: "base" },
      { t: "Pull requests e code review", lv: "base" },
      { t: "GitHub / GitLab / Bitbucket", lv: "base" },
      { t: "Estratégias de branching para times grandes", lv: "mid" },
    ],
  },
  {
    id: "ci",
    label: "CI/CD",
    icon: "⟳",
    color: "#F59E0B",
    items: [
      { t: "Conceitos de integração e entrega contínua", lv: "base" },
      { t: "GitHub Actions", lv: "base" },
      { t: "GitLab CI/CD", lv: "base" },
      { t: "Jenkins", lv: "mid" },
      { t: "ArgoCD (GitOps)", lv: "mid" },
      { t: "Flux CD", lv: "mid" },
      { t: "Estratégias de deploy: blue/green, canary, rolling", lv: "mid" },
      { t: "Pipeline de segurança: SAST, DAST, SBOM", lv: "adv" },
    ],
  },
  {
    id: "containers",
    label: "Containers",
    icon: "▣",
    color: "#38BDF8",
    items: [
      { t: "Docker: imagens, containers, volumes, redes", lv: "base" },
      { t: "Dockerfile: boas práticas e multi-stage build", lv: "base" },
      { t: "Docker Compose", lv: "base" },
      { t: "Registry: Docker Hub, ECR, GCR, Harbor", lv: "mid" },
      { t: "Segurança em containers (scan, rootless)", lv: "mid" },
      { t: "Podman e alternativas ao Docker", lv: "adv" },
    ],
  },
  {
    id: "k8s",
    label: "Kubernetes",
    icon: "✦",
    color: "#6366F1",
    items: [
      { t: "Arquitetura do cluster: nodes, pods, etcd", lv: "base" },
      { t: "Deployments, ReplicaSets, StatefulSets, DaemonSets", lv: "base" },
      { t: "Services, Ingress e DNS interno", lv: "base" },
      { t: "ConfigMaps e Secrets", lv: "base" },
      { t: "Namespaces, RBAC e políticas de rede", lv: "mid" },
      { t: "Helm: criação e uso de charts", lv: "mid" },
      { t: "HPA, VPA e cluster autoscaler", lv: "mid" },
      { t: "Operators e CRDs", lv: "adv" },
      { t: "Kustomize", lv: "mid" },
      { t: "Troubleshooting de clusters em produção", lv: "adv" },
    ],
  },
  {
    id: "iac",
    label: "IaC — Infraestrutura como Código",
    icon: "⌘",
    color: "#34D399",
    items: [
      { t: "Terraform: providers, resources, state", lv: "base" },
      { t: "Módulos e workspaces no Terraform", lv: "mid" },
      { t: "Ansible: playbooks, roles, inventários", lv: "mid" },
      { t: "Pulumi (IaC com linguagens de programação)", lv: "adv" },
      { t: "Gerenciamento de estado remoto e backends", lv: "mid" },
      { t: "Drift detection e terraform plan em CI", lv: "mid" },
      { t: "CDK (AWS Cloud Development Kit)", lv: "adv" },
    ],
  },
  {
    id: "cloud",
    label: "Cloud Providers",
    icon: "⬡",
    color: "#FB923C",
    items: [
      { t: "Fundamentos: regiões, zonas, IAM, billing", lv: "base" },
      { t: "AWS: EC2, VPC, S3, RDS, EKS, Lambda", lv: "base" },
      { t: "GCP: GKE, Cloud Run, BigQuery", lv: "mid" },
      { t: "Azure: AKS, Azure DevOps, AD", lv: "mid" },
      { t: "Multi-cloud e cloud agnostic design", lv: "adv" },
      { t: "FinOps: otimização de custos cloud", lv: "adv" },
    ],
  },
  {
    id: "obs",
    label: "Observabilidade & Monitoramento",
    icon: "◉",
    color: "#F472B6",
    items: [
      { t: "Os 3 pilares: métricas, logs, traces", lv: "base" },
      { t: "Prometheus e Grafana", lv: "base" },
      { t: "ELK Stack (Elasticsearch, Logstash, Kibana)", lv: "mid" },
      { t: "Loki e Grafana para logs", lv: "mid" },
      { t: "Jaeger / Tempo para tracing distribuído", lv: "mid" },
      { t: "OpenTelemetry", lv: "adv" },
      { t: "SLO, SLA, SLI e error budgets", lv: "mid" },
      { t: "Alertas e on-call (PagerDuty, OpsGenie)", lv: "mid" },
    ],
  },
  {
    id: "sec",
    label: "DevSecOps & Segurança",
    icon: "⊛",
    color: "#F87171",
    items: [
      { t: "Gestão de secrets (Vault, AWS Secrets Manager)", lv: "base" },
      { t: "Scanning de imagens (Trivy, Snyk)", lv: "mid" },
      { t: "Políticas de segurança em K8s (OPA, Kyverno)", lv: "mid" },
      { t: "Supply chain security e SLSA", lv: "adv" },
      { t: "CVE management e patch policy", lv: "mid" },
      { t: "Penetration testing básico para infra", lv: "adv" },
    ],
  },
  {
    id: "sre",
    label: "SRE & Confiabilidade",
    icon: "⟁",
    color: "#94A3B8",
    items: [
      { t: "Conceitos de SRE (livro Google SRE)", lv: "mid" },
      { t: "Chaos Engineering (Chaos Monkey, LitmusChaos)", lv: "adv" },
      { t: "Disaster Recovery e RTO/RPO", lv: "mid" },
      { t: "Runbooks e postmortem sem culpa", lv: "mid" },
      { t: "Capacity planning e load testing", lv: "adv" },
    ],
  },
  {
    id: "soft",
    label: "Cultura & Soft Skills",
    icon: "◇",
    color: "#C084FC",
    items: [
      { t: "Metodologias ágeis: Scrum, Kanban", lv: "base" },
      { t: "Comunicação entre Dev e Ops", lv: "base" },
      { t: "Documentação técnica eficaz", lv: "base" },
      { t: "Gestão de incidentes (ITIL básico)", lv: "mid" },
    ],
  },
];
